phoneShop/myapp/urls.py
from django.urls import path
from myapp.views import index, indexItem


app_name = 'myapp'

urlpatterns = [
    # http://127.0.0.1:8000/myapp/
    path("", index),
    path("/<int:my_id>/", indexItem, name='detail'),

]

phoneShop/phoneShop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path("myapp/", include("myapp.urls"), name='myapp'),
    
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

phoneShop/myapp/models.py
from django.db import models

# Create your models here.
class MyProduct(models.Model):
    name = models.CharField(max_length=100)
    price = models.IntegerField()
    description = models.CharField(max_length=200)
    image = models.ImageField(blank=True, upload_to='images')
    
    def __str__(self) -> str:
        return self.name

phoneShop/myapp/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .models import MyProduct
# Create your views here.
def index(request):
    items = MyProduct.objects.all()
    context = {
        'items':items
    }
    return render(request, "myapp/index.html", context)


def indexItem(request, my_id):
    item = MyProduct.objects.get(id=my_id)
    context = {
        'item': item
    }
    return render(request, "myapp/detail.html", context)

phoneShop/myapp/templates/myapp/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'myapp/styles.css' %}">
    <title>Document</title>
</head>
<body>
    {% include './navbar.html' %}

    
    {% block content %}
    {% endblock content %}
    
</body>
</html>

phoneShop/myapp/templates/myapp/detail.html
{% extends "./base.html" %}
{% load humanize %}

  {% block content %}
  <div class="sm:flex md:*:flex-col p-10 w-full h-200 ">
      <img class="w-1/3 sm:*:w-0"src="{{item.image.url}}" alt="ItemPhoto">
      <div class="w-2/3 text-xl ml-10 mt-5">
          <p class=" mt-5">{{item.name}}</p>
          <p class=" mt-5 text-green-500">${{item.price | intcomma}}</p>
          <p class=" mt-5 text-gray-500">{{item.description}}</p>
      </div>
  </div>
  {% endblock content %}

phoneShop/myapp/templates/myapp/index.html
{% extends './base.html' %}
{% block content %}
  <main class="mt-10 mx-auto max-w-7xl px-4 sm:mt-12 sm:px-6 md:mt-16 lg:mt-20 lg:px-8 xl:mt-28">
    <div class="text-center sm:text-center lg:text-left">
      <h1 class="text-4xl font-extrabold text-gray-800 sm:text-5xl md:text-6xl">
        <span class="block xl:inline">Супер товары </span>
        <span class="block xl:inline text-green-500" >По супер ценам</span>
      </h1>
      <p class="mt-3 text-base text-gray-500 sm:mt-5 sm:text-lg sm:max-w-xl sm:mx-auto md:mt-5 md:text-xl lg:mx-0 "> Вы можете заказать товар из любой точки мира!</p>
    </div>
    <div class="p-10 grid grid-cols-1 sm:grid-cols-1 md:grid-cols-3 xl:grid-cols-3 lg:grid-cols-3 gap-3">
      {% for item  in items %}
        <a href="{% url 'myapp:detail' item.id %}">
        <div class="rounded overflow-hidden shadow-lg ">
  
          <img class="w-full h-auto"src="{{item.image.url}}" alt="">
          <div class="px-3 py-6 ">
            <p class="font-bold text-xl mb-2">{{item.name}}</p>
            <p class="font-bold text-xl text-green-500 mb-2">${{item.price}}</p>
            <p class="text-gray-500 text-base">{{item.description}}</p>
  
          </div>
        </div>
      </a>
      {% endfor %}
  
    </div> 
  </main>
{% endblock content %}

        

    
</body>
</html>

phoneShop/myapp/templates/myapp/navbar.html
{% load static %}

<nav class="bg-white shadow-lg">
    <div class="max-w-6xl mx-auto px-4">
      <div class="flex justify-between">
        <div class="flex space-x-7">
          <div>
            <a href="#" class="flex items-center px-2 py-4">
            <img class="h-8 w-8" src="{% static 'myapp/img/shop_img.png' %}" alt="logo">
            <span class="text-gray-500 font-semibold text-xl">Pro Shop</span>
          </a>
        </div>

          <div class="items-center flex space-x-1">
            <a href="#" class="py-4 px-2 text-gray-500 font-semibold border-b-2 border-green-500">Home</a>
            <a href="#" class="py-4 px-2 text-gray-500 font-semibold">About</a>
            <a href="#" class="py-4 px-2 text-gray-500 font-semibold">Contacts</a>
            <a href="#" class="py-4 px-2 text-gray-500 font-semibold">Place</a>

          </div>
        </div>
      </div>
    </div>
  </nav>